export const FILIPINAS_EXPORTACIONES_DESC = {
  "REG_DATE": "Fecha de registro aduanero. Funciona como la 'Fecha Ancla' principal para este conjunto de datos.",
  "ASSESSMENT_DATE": "Fecha de evaluación o liquidación de los impuestos y derechos aduaneros.",
  "COLLECTION_DATE": "Fecha en la que se efectuó la recaudación o el pago de los impuestos aduaneros.",
  "DECLARATION_NO": "Número oficial y completo de la declaración de aduanas.",
  "ITEM_NO": "Número de ítem o artículo secuencial dentro de la declaración aduanera.",
  "DECLARATION_TYPE": "Tipo de declaración basado en categorías aduaneras, como Consumo (4), Importación Temporal (5), Reimportación (6), Almacenamiento (7) o Tránsito (8).",
  "BILL_OF_LADING": "Número de conocimiento de embarque (B/L) o guía aérea. Documento principal de transporte.",
  "VESSEL": "Nombre del buque, barco o medio de transporte que traslada la mercancía.",
  "EXPORTER_CODE": "Número de Identificación Tributaria (TIN) real del exportador.",
  "EXPORTER_NAME": "Nombre o razón social de la empresa exportadora.",
  "EXPORTER_ADDRESS": "Dirección comercial del exportador.",
  "IMPORTER_NAME": "Nombre o razón social del importador (comprador o consignatario en destino).",
  "IMPORTER_ADDRESS": "Dirección comercial del importador en el país de destino.",
  "BROKER_NAME": "Nombre del agente, corredor o despacho de aduanas que gestiona el trámite.",
  "BROKER_ADDRESS": "Dirección del agente de aduanas.",
  "PORT_CODE": "Código oficial del puerto o aeropuerto por donde sale la mercancía.",
  "PORT_NAME": "Nombre del puerto o aeropuerto de salida.",
  "DESTINATION_COUNTRY_NAME": "Nombre del país hacia donde se dirige la exportación.",
  "HS_CODE": "Código arancelario del Sistema Armonizado (HS) que clasifica internacionalmente la mercancía.",
  "PRODUCT_DESC": "Descripción comercial detallada del producto que se está exportando.",
  "MARKS_AND_NUMBERS": "Marcas, números o identificadores impresos en los paquetes o contenedores.",
  "CUSTOMS_PROCEDURE_CODE": "Código de Procedimiento Aduanero (CPC) de 4 dígitos. Identifica procedimientos extendidos, como 'Exportación permanente directa' (1000) o 'Reexportación tras depósito aduanero' (3071).",
  "NATL_PROC_CODE": "Código del procedimiento aduanero a nivel nacional (específico de Filipinas).",
  "NATL_PROC_NAME": "Nombre o descripción del procedimiento nacional utilizado.",
  "G_WEIGHT": "Peso bruto total de las mercancías, incluyendo envases y embalajes (Gross Weight).",
  "N_WEIGHT": "Peso neto total de las mercancías, sin considerar el peso del embalaje exterior (Net Weight).",
  "PACKAGES": "Cantidad total de bultos o paquetes.",
  "TYPE_OF_PACKAGES": "Tipo de embalaje utilizado (por ejemplo: cajas, palets, barriles, contenedores).",
  "CUSTOMS_VALUE_IN_FC": "Valor de la mercancía en la aduana expresado en la moneda extranjera original.",
  "FOREIGN_CURRENCY": "Código de la moneda extranjera en la que se realizó la transacción comercial.",
  "DUTIABLE_VALUE_PHP": "Valor en aduana sobre el cual se calculan los impuestos, convertido a Pesos Filipinos (PHP).",
  "INCOTERMS": "Términos Internacionales de Comercio que definen las responsabilidades (ej. FOB, CIF, EXW).",
  "PREF_CODE": "Código de preferencia arancelaria aplicado (si aplica algún tratado de libre comercio).",
  "EXCHANGE_RATE": "Tipo de cambio oficial utilizado en la declaración aduanera.",
  "ENTRY_NO": "Número de flujo de declaración simplificado interno (4-6 dígitos). Coincide de manera 1:1 con el número de declaración pero sin prefijos de puerto/año.",
  "REFERENCE_NO": "Número de referencia interna o número dado por el cliente para rastrear la exportación.",
  "REGISTRATION_NO": "Número de registro otorgado por el sistema aduanero.",
  "ORIGIN_COUNTRY_CODE": "Código ISO del país donde se fabricó u originó la mercancía.",
  "ORIGIN_COUNTRY": "Nombre del país de origen de la mercancía.",
  "QTY": "Cantidad comercial de la mercancía exportada.",
  "UOM": "Unidad de medida para la cantidad declarada (ej. Kilogramos, Litros, Piezas).",
  "PREPAID_ACCNT": "Cuenta prepagada utilizada para cubrir derechos y tarifas de aduana.",
  "ASMTNO": "Número de liquidación o tasación (Assessment number).",
  "RECEIPT_NO": "Número de recibo de los pagos realizados en aduana.",
  "ORIGIN_PROVINCE": "Provincia dentro de Filipinas de donde proviene la mercancía de exportación.",
  "E_YEAR": "Año correspondiente al registro o embarque de la exportación.",
  "E_SERIAL": "Número de serie o correlativo interno de la declaración de exportación.",
  "MODEL_DECLARATION": "Modelo específico de declaración, representado por un código como 4A para Evaluación Anticipada o 6A para Reimportación en el mismo estado.",
  "TOTAL_ITEM": "Cantidad total de artículos/partidas declarados dentro de un mismo despacho.",
  "TOTAL_PACK": "Cantidad total agregada de bultos o envases de todo el envío.",
  "COUNTRY_EXPORT": "País desde el cual se efectúa la exportación (normalmente Filipinas).",
  "TENTATIVE": "Indicador de si la declaración o liquidación tiene carácter provisional/tentativo.",
  "LOC_GOODS": "Ubicación física o almacén donde se encuentran las mercancías antes del embarque.",
  "DUTIES_TAXES": "Suma total de los derechos (aranceles) e impuestos aduaneros a pagar.",
  "QUOTAS": "Información sobre contingentes o cuotas aplicables al producto exportado.",
  "FREIGHT": "Costo del flete o transporte principal.",
  "FREIGHT_CURRENCY": "Moneda en la cual está expresado el costo del flete.",
  "INSURANCE": "Costo del seguro de la mercancía durante su transporte.",
  "INSURANCE_CURRENCY": "Moneda en la cual está expresado el costo del seguro.",
  "ARRASTRE": "Tarifa portuaria por servicios de manipulación de la carga (arrastre) en la terminal.",
  "DUTY_TAX_BASE": "Base imponible sobre la cual se calcula el arancel o derecho de aduana.",
  "DUTY_RATE": "Tasa o porcentaje (%) de arancel o derecho de aduana aplicado.",
  "DUTY_PAID": "Monto pagado en concepto de aranceles o derechos de aduana.",
  "VAT_TAX_BASE": "Base imponible para calcular el IVA (Impuesto al Valor Agregado).",
  "VAT_PAID": "Monto del IVA pagado.",
  "EXCAVT_TAX_BASE": "Base imponible para el cálculo de impuestos especiales/selectivos (Excise Tax).",
  "EXCAVT_TAX_RATE": "Tasa aplicable al impuesto especial (Excise Tax).",
  "EXCISE_ADVALOREM": "Impuesto selectivo al consumo ad-valorem (basado en el valor del producto).",
  "FINE_PENALTIES": "Multas, sanciones o recargos generados por demoras o errores.",
  "SGD_TAX_BASE": "Base imponible para el cálculo de la medida de salvaguardia (Safeguard Duty).",
  "SGD_TAX_RATE": "Tasa porcentual aplicable a la medida de salvaguardia.",
  "SAFE_GUARD_DUTY": "Monto pagado por concepto de derechos de salvaguardia para proteger la industria nacional.",
  "OTHER_TAXES": "Otros impuestos o tasas menores aplicadas a la mercancía.",
  "WHOUSE_CODE": "Código de identificación del almacén fiscal o aduanero.",
  "ASMTSER": "Número de serie del documento de liquidación/tasación aduanera.",
  "RCPTSER": "Número de serie del recibo de pago de los derechos aduaneros.",
  "GUARANTEED_AMT": "Monto respaldado mediante fianzas, cauciones o garantías bancarias aduaneras.",
  "TOTAL_FEES": "Total de cuotas, honorarios de procesamiento y otras tasas administrativas cobradas.",
  "TOTAL_ASSESSMENT": "Monto total evaluado a pagar (suma de derechos, impuestos, multas y tasas).",
  "FOB_USD": "Valor 'Free On Board' de la exportación expresado estrictamente en Dólares Estadounidenses (USD).",
  "DESCRIPCION_PARTIDA": "Descripción de la partida o subpartida arancelaria. Es el texto estandarizado (asociado al HS_CODE) que describe técnica y legalmente la naturaleza de la mercancía."
};

export const FILIPINAS_IMPORTACIONES_DESC = {
  "DAY": "Día en que se registró o tramitó la importación.",
  "MONTH": "Mes correspondiente a la transacción de importación.",
  "YEAR": "Año de la transacción.",
  "AIRWAY_OR_HOUSE_BILL_ID": "Número de la guía aérea (AWB) o conocimiento de embarque (Bill of Lading) que ampara la carga.",
  "HS_CODE": "Código arancelario del Sistema Armonizado (HS) que clasifica la mercancía importada.",
  "PRODUCT_DESC": "Descripción comercial detallada del producto importado.",
  "IMPORTER_NAME": "Nombre o razón social de la empresa que realiza la importación (consignatario).",
  "IMPORTER_ADDRESS": "Dirección comercial o fiscal del importador.",
  "EXPORTER_NAME": "Nombre o razón social del proveedor o exportador en el país de origen.",
  "G_WEIGHT": "Peso bruto total de las mercancías importadas (incluye empaque).",
  "N_WEIGHT": "Peso neto total de las mercancías importadas (sin empaque exterior).",
  "PACKAGES": "Cantidad total de bultos o paquetes.",
  "TYPE_OF_PACKAGES": "Tipo de embalaje utilizado (ej. cajas, palets, bidones).",
  "QUANTITY": "Cantidad comercial de la mercancía importada.",
  "UNIT_OF_QUANTITY": "Unidad de medida para la cantidad declarada (ej. Kilogramos, Unidades, Litros).",
  "FOB_IN_FC": "Valor FOB (Free on Board) expresado en la moneda extranjera original de la transacción.",
  "FREIGHT_IN_FC": "Costo del flete expresado en moneda extranjera.",
  "INSURANCE_IN_FC": "Costo del seguro expresado en moneda extranjera.",
  "CIF_IN_FC": "Valor CIF (Costo, Seguro y Flete) expresado en moneda extranjera.",
  "EXCHANGE_RATE": "Tipo de cambio oficial utilizado para convertir el valor a la moneda local.",
  "FOREIGN_CURRENCY": "Código de la moneda extranjera en la que se negoció la importación (ej. USD, EUR).",
  "CIF_IN_PESO": "Valor CIF (Costo, Seguro y Flete) convertido a Pesos Filipinos (PHP). Base para los impuestos.",
  "PORT_OF_CLEARANCE": "Puerto o aduana por donde se realizó el desaduanaje o nacionalización de la mercancía.",
  "ORIGIN_COUNTRY": "País donde se fabricó, cultivó o extrajo la mercancía.",
  "VESSEL_NAME": "Nombre del barco, vuelo o medio de transporte que trajo la mercancía.",
  "INCOTERMS": "Términos de comercio internacional bajo los cuales se negoció la compra (ej. CIF, FOB, EXW).",
  "IMPORTER_EMAIL": "Correo electrónico de contacto del importador.",
  "IMPORTER_PHONE": "Número de teléfono de contacto del importador.",
  "EXPORT_COUNTRY": "País desde el cual se despachó o envió directamente la mercancía hacia Filipinas.",
  "PORT": "Código o nombre del puerto de entrada.",
  "E_SERIAL": "Número de serie o identificador interno del sistema aduanero.",
  "ENTRY_NO": "Número de flujo de la declaración simplificada de ingreso (identificador del despacho).",
  "GREEN": "Canal de selectividad Verde: Levante automático, sin revisión física ni documental.",
  "BLUE": "Canal de selectividad Azul: Levante automático pero sujeto a auditoría a posteriori.",
  "ORANGE": "Canal de selectividad Naranja: Revisión de documentos requerida antes del levante.",
  "YELLOW": "Canal de selectividad Amarillo: Usualmente indica revisión de documentos (varía según sistema específico).",
  "RED": "Canal de selectividad Rojo: Requiere inspección física de la mercancía y revisión documental.",
  "TYPE_DECLARATION": "Tipo de declaración, con categorías como Consumo (4), Importación temporal (5), Reimportación (6), etc..",
  "MODEL_DECLARATION": "Modelo específico de declaración, como 4000 (Entrada directa para uso interno) o 5200 (Importación temporal bajo fianza).",
  "TOTAL_ASSESSMENT": "Monto total liquidado por la aduana (impuestos, derechos y otras tasas).",
  "REGISTRY_DATE": "Fecha en la que la declaración de importación fue registrada oficialmente.",
  "ASESSMENT_DATE": "Fecha en la que se evaluaron y calcularon los derechos e impuestos a pagar.",
  "COLLECTION_DATE": "Fecha en la que se realizó el pago a la aduana.",
  "MANIFEST": "Número del manifiesto de carga del medio de transporte.",
  "WHOUSE_CODE": "Código del almacén aduanero o depósito temporal donde se guardó la carga.",
  "LOC_GOODS": "Ubicación física actual de las mercancías durante el trámite.",
  "NO_OF_CONTAINER": "Cantidad total de contenedores que conforman la importación.",
  "BROKER": "Nombre del agente de aduanas que representa al importador.",
  "PORT_1": "Código complementario del puerto o aduana de destino.",
  "DESTINATION": "Lugar, provincia o ciudad de destino final de la mercancía dentro del país.",
  "ESERIAL_1": "Número de serie secundario o código de control adicional de la importación.",
  "ITEM_NO": "Número del ítem o artículo secuencial dentro de la declaración.",
  "PROCEDURE_CODE": "Código del Procedimiento Aduanero (CPC) de 4 dígitos. Por ejemplo, 4000 para uso interno.",
  "NATIONAL_CODE": "Código nacional de trámite aduanero, específico para normativas locales.",
  "PREF_CODE": "Código que indica si se aplicó alguna preferencia arancelaria (TLC).",
  "DUTY_RATE": "Porcentaje (%) de derecho o arancel de aduana aplicado a la mercancía.",
  "DUTY_PAID": "Monto pagado por concepto de derechos o aranceles de importación.",
  "VAT_PAID": "Monto pagado por concepto de Impuesto al Valor Agregado (IVA).",
  "EXCISE_ADVALOREM": "Impuesto selectivo al consumo ad-valorem pagado sobre ciertos bienes específicos.",
  "FINE_PENALTIES": "Multas o penalizaciones cobradas por infracciones o demoras.",
  "OTHER_TAXES": "Otros impuestos o gravámenes aplicados en la importación.",
  "DUTIES_TAXES": "Suma total de los aranceles (Duties) y los impuestos (Taxes) regulares.",
  "TOTAL_FEES": "Suma total de las tarifas administrativas, honorarios y procesamientos aduaneros.",
  "CONSIGNEE_TIN": "Número de Identificación Tributaria (TIN) del consignatario/importador.",
  "BROKER_TIN": "Número de Identificación Tributaria (TIN) del agente o corredor de aduanas.",
  "FOB": "Valor Free On Board total de la importación (usualmente la base principal de cálculo).",
  "VAT_TAX_BASE": "Base imponible sobre la cual se calculó el Impuesto al Valor Agregado (IVA).",
  "REFERENCE_NO": "Número de referencia interno del importador o del agente.",
  "COUNTRY_ORIGIN_1": "Campo alternativo para designar o confirmar el país de origen.",
  "CONTAINER_NO": "Los números alfanuméricos de identificación (siglas) de los contenedores específicos utilizados.",
  "BROKER_ADD": "Dirección comercial del agente de aduanas.",
  "EXPORTER_ADD": "Dirección comercial del proveedor/exportador en origen.",
  "CIF_USD": "Valor CIF (Costo, Seguro y Flete) expresado estrictamente en Dólares Estadounidenses (USD).",
  "DESCRIPCION_PARTIDA": "Descripción oficial de la partida o subpartida arancelaria correspondiente al HS_CODE declarado."
};

export const FILIPINAS_PARTIDAS_DESC = {
  "HS_CODE": "Código arancelario del Sistema Armonizado (HS) que clasifica la mercancía.",
  "DESCRIPCION_PARTIDA": "Descripción oficial de la partida o subpartida arancelaria correspondiente al HS_CODE declarado."
};

export const getColumnDescription = (dbName, tableName, columnName) => {
  if (!dbName || !tableName || !columnName) return "";

  const dbKey = dbName.toUpperCase();

  if (dbKey === "FILIPINAS") {
    const tableLower = tableName.toLowerCase();
    const colUpper = columnName.toUpperCase();

    if (tableLower.includes("exportaciones")) {
      return FILIPINAS_EXPORTACIONES_DESC[colUpper] || "";
    }
    
    if (tableLower.includes("importaciones")) {
      return FILIPINAS_IMPORTACIONES_DESC[colUpper] || "";
    }

    if (tableLower.includes("partidas")) {
      return FILIPINAS_PARTIDAS_DESC[colUpper] || "";
    }
  }

  return "";
};