// ─────────────────────────────────────────────────────────────────────────────
// COLUMNAS PRIORITARIAS — Orden canónico (flujo Proceso → Producción)
// Usadas por MappingModal, ProcesoTempProModal y ValidationModal para
// mostrar primero las columnas clave y luego el resto alfabéticamente.
// ─────────────────────────────────────────────────────────────────────────────

/** Columnas clave de Exportaciones_* en orden canónico */
export const EXPO_PRIORITY_COLUMNS = [
  "ASSESSMENT_DATE",
  "REFERENCE_NO",
  "DECLARATION_NO",
  "ITEM_NO",
  "HS_CODE",
  "BILL_OF_LADING",
  "EXPORTER_CODE",
  "EXPORTER_NAME",
  "IMPORTER_NAME",
  "BROKER_NAME",
  "ORIGIN_COUNTRY",
  "DESTINATION_COUNTRY_NAME",
  "PORT_CODE",
  "PORT_NAME",
  "VESSEL",
  "PRODUCT_DESC",
  "G_WEIGHT",
  "N_WEIGHT",
  "QTY",
  "PACKAGES",
  "TYPE_OF_PACKAGES",
  "UOM",
  "DUTIABLE_VALUE_PHP",
  "FOB_USD",
  "INCOTERMS",
];

/** Columnas clave de Importaciones_* en orden canónico */
export const IMPO_PRIORITY_COLUMNS = [
  "REGISTRY_DATE",
  "REFERENCE_NO",
  "MANIFEST",
  "AIRWAY_OR_HOUSE_BILL_ID",
  "CONTAINER_NO",
  "ITEM_NO",
  "HS_CODE",
  "CONSIGNEE_TIN",
  "IMPORTER_NAME",
  "EXPORTER_NAME",
  "BROKER_TIN",
  "BROKER",
  "ORIGIN_COUNTRY",
  "EXPORT_COUNTRY",
  "PORT_1",
  "VESSEL_NAME",
  "PRODUCT_DESC",
  "G_WEIGHT",
  "N_WEIGHT",
  "QUANTITY",
  "PACKAGES",
  "TYPE_OF_PACKAGES",
  "UNIT_OF_QUANTITY",
  "FOB_USD",
  "FREIGHT_USD",
  "INSURANCE_USD",
  "CIF_IN_PESO",
  "INCOTERMS",
];

// ─────────────────────────────────────────────────────────────────────────────
// MAPEO Temp_Proceso — EXPORTACIONES
// t1 = Temp_Expo_PH  ·  t2 = Temp_Exp_PH  ·  t3 = Exportaciones_*
// Orden: columnas prioritarias primero (imagen referencia), luego resto A-Z
// ─────────────────────────────────────────────────────────────────────────────
export const TEMP_PROCESO_MAPPINGS = [
  // ── Columnas prioritarias (flujo proceso → producción) ─────────────────────
  { t1: "ASSESSMENT_DATE",          t2: "ASESSMENTDATE",        t3: "ASSESSMENT_DATE" },
  { t1: "REFERENCE_NO",             t2: "REFERENCENO",          t3: "REFERENCE_NO" },
  { t1: "DECLARATION_NO",           t2: "DECLARATION_NO",       t3: "DECLARATION_NO" },
  { t1: "ITEM_NO",                  t2: "ITEM_NO",              t3: "ITEM_NO" },
  { t1: "HS_CODE",                  t2: "HSCODE",               t3: "HS_CODE" },
  { t1: "BILL_OF_LADING",           t2: "BL",                   t3: "BILL_OF_LADING" },
  { t1: "EXPORTER_CODE",            t2: "EXPORTERTIN",          t3: "EXPORTER_CODE" },
  { t1: "EXPORTER_NAME",            t2: "EXPORTER",             t3: "EXPORTER_NAME" },
  { t1: "IMPORTER_NAME",            t2: "CONSIGNEE",            t3: "IMPORTER_NAME" },
  { t1: "BROKER_NAME",              t2: "BROKER",               t3: "BROKER_NAME" },
  { t1: "ORIGIN_COUNTRY",           t2: "ORIGIN_COUNTRY",       t3: "ORIGIN_COUNTRY" },
  { t1: "DESTINATION_COUNTRY_NAME", t2: "COUNTRYOFDESTINATION", t3: "DESTINATION_COUNTRY_NAME" },
  { t1: "PORT_CODE",                t2: "PORT_CODE",            t3: "PORT_CODE" },
  { t1: "PORT_NAME",                t2: "PORT",                 t3: "PORT_NAME" },
  { t1: "VESSEL",                   t2: "VESSEL",               t3: "VESSEL" },
  { t1: "PRODUCT_DESC",             t2: "GOODSDESCRIPTION",     t3: "PRODUCT_DESC" },
  { t1: "G_WEIGHT",                 t2: "GROSSMASSKGS",         t3: "G_WEIGHT" },
  { t1: "N_WEIGHT",                 t2: "NETMASSKGS",           t3: "N_WEIGHT" },
  { t1: "QTY",                      t2: "QUANTITY",             t3: "QTY" },
  { t1: "PACKAGES",                 t2: "NOPACKAGES",           t3: "PACKAGES" },
  { t1: "TYPE_OF_PACKAGES",         t2: "TYPEPKGS",             t3: "TYPE_OF_PACKAGES" },
  { t1: "UOM",                      t2: "SUPP_UNITS",           t3: "UOM" },
  { t1: "DUTIABLE_VALUE_PHP",       t2: "DUTIABLEVALUEPHP",     t3: "DUTIABLE_VALUE_PHP" },
  { t1: "FOB_USD",                  t2: "FOB_USD",              t3: "FOB_USD" },
  { t1: "INCOTERMS",                t2: "TERMSOFDELIVERY",      t3: "INCOTERMS" },
  // ── Resto de columnas (A-Z por t3) ────────────────────────────────────────
  { t1: "ARRASTRE",                 t2: "ARRASTRE",             t3: "ARRASTRE" },
  { t1: "ASMTNO",                   t2: "ASMTNO",               t3: "ASMTNO" },
  { t1: "ASMTSER",                  t2: "ASMTSER",              t3: "ASMTSER" },
  { t1: "BROKER_ADDRESS",           t2: "BROKER_ADDRESS",       t3: "BROKER_ADDRESS" },
  { t1: "COLLECTION_DATE",          t2: "COLLECTIONDATE",       t3: "COLLECTION_DATE" },
  { t1: "COUNTRY_EXPORT",           t2: "COUNTRYEXPORT",        t3: "COUNTRY_EXPORT" },
  { t1: "CUSTOMS_PROCEDURE_CODE",   t2: "PROCEDURECODE",        t3: "CUSTOMS_PROCEDURE_CODE" },
  { t1: "CUSTOMS_VALUE_IN_FC",      t2: "CUSTOMSVALUE",         t3: "CUSTOMS_VALUE_IN_FC" },
  { t1: "DECLARATION_TYPE",         t2: "TYPEDECLARATION",      t3: "DECLARATION_TYPE" },
  { t1: null,                       t2: null,                   t3: "DESCRIPCION_PARTIDA" },
  { t1: "DUTIES_TAXES",             t2: "DUTIESTAXES",          t3: "DUTIES_TAXES" },
  { t1: "DUTY_PAID",                t2: "DUTY_PAID",            t3: "DUTY_PAID" },
  { t1: "DUTY_RATE",                t2: "DUTYRATE",             t3: "DUTY_RATE" },
  { t1: "DUTY_TAX_BASE",            t2: "DUTYTAXBASE",          t3: "DUTY_TAX_BASE" },
  { t1: "ENTRY_NO",                 t2: "ENTRYNO",              t3: "ENTRY_NO" },
  { t1: "E_SERIAL",                 t2: "ESERIAL",              t3: "E_SERIAL" },
  { t1: "E_YEAR",                   t2: "EYEAR",                t3: "E_YEAR" },
  { t1: "EXCAVT_TAX_BASE",          t2: "EXCAVTTAXBASE",        t3: "EXCAVT_TAX_BASE" },
  { t1: "EXCAVT_TAX_RATE",          t2: "EXCAVTTAXRATE",        t3: "EXCAVT_TAX_RATE" },
  { t1: "EXCISE_ADVALOREM",         t2: "EXCISEADVALOREM",      t3: "EXCISE_ADVALOREM" },
  { t1: "EXCHANGE_RATE",            t2: "EXCHANGE_RATE",        t3: "EXCHANGE_RATE" },
  { t1: "EXPORTER_ADDRESS",         t2: "EXPORTER_ADDRESS",     t3: "EXPORTER_ADDRESS" },
  { t1: "FINE_PENALTIES",           t2: "FINEPENALTIES",        t3: "FINE_PENALTIES" },
  { t1: "FOREIGN_CURRENCY",         t2: "CURRENCY",             t3: "FOREIGN_CURRENCY" },
  { t1: "FREIGHT",                  t2: "FREIGHT",              t3: "FREIGHT" },
  { t1: "FREIGHT_CURRENCY",         t2: "FREIGHT_CURRENCY",     t3: "FREIGHT_CURRENCY" },
  { t1: "GUARANTEED_AMT",           t2: "GUARANTEEDAMT",        t3: "GUARANTEED_AMT" },
  { t1: "IMPORTER_ADDRESS",         t2: "IMPORTER_ADDRESS",     t3: "IMPORTER_ADDRESS" },
  { t1: "INSURANCE",                t2: "INSURANCE",            t3: "INSURANCE" },
  { t1: "INSURANCE_CURRENCY",       t2: "INSURANCE_CURRENCY",   t3: "INSURANCE_CURRENCY" },
  { t1: "LOC_GOODS",                t2: "LOCGOODS",             t3: "LOC_GOODS" },
  { t1: "MARKS_AND_NUMBERS",        t2: "MARKS_AND_NUMBERS",    t3: "MARKS_AND_NUMBERS" },
  { t1: "MODEL_DECLARATION",        t2: "MODELDECLARATION",     t3: "MODEL_DECLARATION" },
  { t1: "NATL_PROC_CODE",           t2: "NATIONALCODE",         t3: "NATL_PROC_CODE" },
  { t1: "NATL_PROC_NAME",           t2: "NATL_PROC_NAME",       t3: "NATL_PROC_NAME" },
  { t1: "ORIGIN_COUNTRY_CODE",      t2: "COUNTRYORIGIN",        t3: "ORIGIN_COUNTRY_CODE" },
  { t1: "ORIGIN_PROVINCE",          t2: "PROVINCE_ORIGIN",      t3: "ORIGIN_PROVINCE" },
  { t1: "OTHER_TAXES",              t2: "OTHERTAXES",           t3: "OTHER_TAXES" },
  { t1: "PREF_CODE",                t2: "PREF_CODE",            t3: "PREF_CODE" },
  { t1: "PREPAID_ACCNT",            t2: "PREPAIDACCNT",         t3: "PREPAID_ACCNT" },
  { t1: "QUOTAS",                   t2: "QUOTAS",               t3: "QUOTAS" },
  { t1: "RCPTSER",                  t2: "RCPTSER",              t3: "RCPTSER" },
  { t1: "RECEIPT_NO",               t2: "RECEIPTNO",            t3: "RECEIPT_NO" },
  { t1: "REG_DATE",                 t2: "REGISTRYDATE",         t3: "REG_DATE" },
  { t1: "REGISTRATION_NO",          t2: "REGISTRATIONNO",       t3: "REGISTRATION_NO" },
  { t1: "SAFE_GUARD_DUTY",          t2: "SAFEGUARDDUTY",        t3: "SAFE_GUARD_DUTY" },
  { t1: "SGD_TAX_BASE",             t2: "SGDTAXBASE",           t3: "SGD_TAX_BASE" },
  { t1: "SGD_TAX_RATE",             t2: "SGDTAXRATE",           t3: "SGD_TAX_RATE" },
  { t1: "TENTATIVE",                t2: "TENTATIVE",            t3: "TENTATIVE" },
  { t1: "TOTAL_ASSESSMENT",         t2: "TOTALASSESSMENT",      t3: "TOTAL_ASSESSMENT" },
  { t1: "TOTAL_FEES",               t2: "TOTALFEES",            t3: "TOTAL_FEES" },
  { t1: "TOTAL_ITEM",               t2: "TOTAL_ITEM",           t3: "TOTAL_ITEM" },
  { t1: "TOTAL_PACK",               t2: "TOTAL_PACK",           t3: "TOTAL_PACK" },
  { t1: "VAT_PAID",                 t2: "VAT_PAID",             t3: "VAT_PAID" },
  { t1: "VAT_TAX_BASE",             t2: "VATTAXBASE",           t3: "VAT_TAX_BASE" },
  { t1: "WHOUSE_CODE",              t2: "WHOUSECODE",           t3: "WHOUSE_CODE" },
];

// ─────────────────────────────────────────────────────────────────────────────
// MAPEO Proceso_Temp_Pro — IMPORTACIONES
// t1 = Temp_Impo_PH  ·  t2 = Temp_Imp_PH  ·  t3 = Importaciones_*
// Orden: columnas prioritarias primero (imagen referencia), luego resto A-Z
// ─────────────────────────────────────────────────────────────────────────────
export const PROCESO_TEMP_PRO_MAPPINGS = [
  // ── Columnas prioritarias (flujo proceso → producción) ─────────────────────
  // t1 = Temp_Impo_PH  ·  t2 = Temp_Imp_PH  ·  t3 = Importaciones_*
  { t1: "REGISTRY_DATE",            t2: "REGISTRYDATE",      t3: "REGISTRY_DATE" },
  { t1: "REFERENCE_NO",             t2: "REFERENCENO",       t3: "REFERENCE_NO" },
  { t1: "MANIFEST",                 t2: "MANIFEST",          t3: "MANIFEST" },
  { t1: "AIRWAY_OR_HOUSE_BILL_ID",  t2: "BL",                t3: "AIRWAY_OR_HOUSE_BILL_ID" },
  { t1: "CONTAINER_NO",             t2: "CONTAINERNO",       t3: "CONTAINER_NO" },
  { t1: "ITEM_NO",                  t2: "ITEM_NO",           t3: "ITEM_NO" },
  { t1: "HS_CODE",                  t2: "HSCODE",            t3: "HS_CODE" },
  { t1: "CONSIGNEE_TIN",            t2: "CONSIGNEETIN",      t3: "CONSIGNEE_TIN" },
  { t1: "IMPORTER_NAME",            t2: "CONSIGNEE",         t3: "IMPORTER_NAME" },
  { t1: "EXPORTER_NAME",            t2: "EXPORTER",          t3: "EXPORTER_NAME" },
  { t1: "BROKER_TIN",               t2: "BROKERTIN",         t3: "BROKER_TIN" },
  { t1: "BROKER",                   t2: "BROKER",            t3: "BROKER" },
  { t1: "ORIGIN_COUNTRY",           t2: "COUNTRYORIGIN_1",   t3: "ORIGIN_COUNTRY" },
  { t1: "EXPORT_COUNTRY",           t2: "COUNTRYEXPORT",     t3: "EXPORT_COUNTRY" },
  { t1: "PORT_1",                   t2: "PORT_1",            t3: "PORT_1" },
  { t1: "VESSEL_NAME",              t2: "VESSEL",            t3: "VESSEL_NAME" },
  { t1: "PRODUCT_DESC",             t2: "GOODSDESCRIPTION",  t3: "PRODUCT_DESC" },
  { t1: "G_WEIGHT",                 t2: "GROSSMASSKGS",      t3: "G_WEIGHT" },
  { t1: "N_WEIGHT",                 t2: "NETMASSKGS",        t3: "N_WEIGHT" },
  { t1: "QUANTITY",                 t2: "QUANTITY",          t3: "QUANTITY" },
  { t1: "PACKAGES",                 t2: "NOPACKAGES",        t3: "PACKAGES" },
  { t1: "TYPE_OF_PACKAGES",         t2: "TYPEPKGS",          t3: "TYPE_OF_PACKAGES" },
  { t1: "UNIT_OF_QUANTITY",         t2: "SUPP_UNITS",        t3: "UNIT_OF_QUANTITY" },
  { t1: null,                       t2: null,                t3: "FOB_USD" },
  { t1: null,                       t2: null,                t3: "FREIGHT_USD" },
  { t1: null,                       t2: null,                t3: "INSURANCE_USD" },
  { t1: "CIF_IN_PESO",              t2: "DUTIABLEVALUEPHP",  t3: "CIF_IN_PESO" },
  { t1: "INCOTERMS",                t2: "TERMSOFDELIVERY",   t3: "INCOTERMS" },
  // ── Resto de columnas (A-Z por t3) ────────────────────────────────────────
  { t1: "ASESMENT_DATE",            t2: "ASESSMENTDATE",     t3: "ASESSMENT_DATE" },
  { t1: "BLUE",                     t2: "BLUE",              t3: "BLUE" },
  { t1: "BROKER_ADD",               t2: "BROKERADD",         t3: "BROKER_ADD" },
  { t1: "CIF_IN_FC",                t2: "DUTIABLE_FOREIGN",  t3: "CIF_IN_FC" },
  { t1: "CIF_USD",                  t2: "CIF_USD",           t3: "CIF_USD" },
  { t1: "COLLECTION_DATE",          t2: "COLLECTIONDATE",    t3: "COLLECTION_DATE" },
  { t1: "COUNTRY_ORIGIN_1",         t2: "COUNTRYORIGIN",     t3: "COUNTRY_ORIGIN_1" },
  { t1: "DAY",                      t2: "DAY",               t3: "DAY" },
  { t1: null,                       t2: null,                t3: "DESCRIPCION_PARTIDA" },
  { t1: "DESTINATION",              t2: "DESTINATION",       t3: "DESTINATION" },
  { t1: "DUTIES_TAXES",             t2: "DUTIESTAXES",       t3: "DUTIES_TAXES" },
  { t1: "DUTY_PAID",                t2: "DUTY_PAID",         t3: "DUTY_PAID" },
  { t1: "DUTY_RATE",                t2: "DUTYRATE",          t3: "DUTY_RATE" },
  { t1: "E_SERIAL",                 t2: "ESERIAL",           t3: "E_SERIAL" },
  { t1: "ENTRY_NO",                 t2: "ENTRYNO",           t3: "ENTRY_NO" },
  { t1: "ESERIAL_1",                t2: "ESERIAL_1",         t3: "ESERIAL_1" },
  { t1: "EXCHANGE_RATE",            t2: "EXCHANGE_RATE",     t3: "EXCHANGE_RATE" },
  { t1: "EXCISE_ADVALOREM",         t2: "EXCISEADVALOREM",   t3: "EXCISE_ADVALOREM" },
  { t1: "EXPORTER_ADD",             t2: "EXPORTERADD",       t3: "EXPORTER_ADD" },
  { t1: "FINE_PENALTIES",           t2: "FINEPENALTIES",     t3: "FINE_PENALTIES" },
  { t1: "FOB",                      t2: "FOB",               t3: "FOB" },
  { t1: "FOB_IN_FC",                t2: "CUSTOMSVALUE",      t3: "FOB_IN_FC" },
  { t1: "FOREIGN_CURRENCY",         t2: "CURRENCY",          t3: "FOREIGN_CURRENCY" },
  { t1: "FREIGHT_IN_FC",            t2: "FREIGHT",           t3: "FREIGHT_IN_FC" },
  { t1: "GREEN",                    t2: "GREEN",             t3: "GREEN" },
  { t1: "IMPORTER_ADDRESS",         t2: "CONSIGNEEADD",      t3: "IMPORTER_ADDRESS" },
  { t1: "IMPORTER_EMAIL",           t2: "IMPORTER_EMAIL",    t3: "IMPORTER_EMAIL" },
  { t1: "IMPORTER_PHONE",           t2: "IMPORTER_PHONE",    t3: "IMPORTER_PHONE" },
  { t1: "INSURANCE_IN_FC",          t2: "INSURANCE",         t3: "INSURANCE_IN_FC" },
  { t1: "LOC_GOODS",                t2: "LOCGOODS",          t3: "LOC_GOODS" },
  { t1: "MODEL_DECLARATION",        t2: "MODELDECLARATION",  t3: "MODEL_DECLARATION" },
  { t1: "MONTH",                    t2: "MONTH",             t3: "MONTH" },
  { t1: "NATIONAL_CODE",            t2: "NATIONALCODE",      t3: "NATIONAL_CODE" },
  { t1: "NO_OF_CONTAINER",          t2: "NOOFCONTAINER",     t3: "NO_OF_CONTAINER" },
  { t1: "ORANGE",                   t2: "ORANGE",            t3: "ORANGE" },
  { t1: "OTHER_TAXES",              t2: "OTHERTAXES",        t3: "OTHER_TAXES" },
  { t1: "PORT",                     t2: "PORT",              t3: "PORT" },
  { t1: "PORT_OF_CLEARANCE",        t2: "PORTOFENTRY",       t3: "PORT_OF_CLEARANCE" },
  { t1: "PREF_CODE",                t2: "PREF_CODE",         t3: "PREF_CODE" },
  { t1: "PROCEDURE_CODE",           t2: "PROCEDURECODE",     t3: "PROCEDURE_CODE" },
  { t1: "RED",                      t2: "RED",               t3: "RED" },
  { t1: "TOTAL_ASSESSMENT",         t2: "TOTALASSESSMENT",   t3: "TOTAL_ASSESSMENT" },
  { t1: "TOTAL_FEES",               t2: "TOTALFEES",         t3: "TOTAL_FEES" },
  { t1: "TYPE_DECLARATION",         t2: "TYPEDECLARATION",   t3: "TYPE_DECLARATION" },
  { t1: "VAT_PAID",                 t2: "VAT_PAID",          t3: "VAT_PAID" },
  { t1: "VAT_TAX_BASE",             t2: "VATTAXBASE",        t3: "VAT_TAX_BASE" },
  { t1: "WHOUSE_CODE",              t2: "WHOUSECODE",        t3: "WHOUSE_CODE" },
  { t1: "YEAR",                     t2: "EYEAR",             t3: "YEAR" },
  { t1: "YELLOW",                   t2: "YELLOW",            t3: "YELLOW" },
];

// ─────────────────────────────────────────────────────────────────────────────
// CONFIGURACIÓN DE MODALES
// ─────────────────────────────────────────────────────────────────────────────
export const MAPPING_CONFIG = {
  exports: {
    title: "Relación: Proceso de Exportaciones",
    tables: ["Temp_Expo_PH", "Temp_Exp_PH"],
    mapping: TEMP_PROCESO_MAPPINGS,
  },
  imports: {
    title: "Relación: Proceso de Importaciones",
    tables: ["Temp_Impo_PH", "Temp_Imp_PH"],
    mapping: PROCESO_TEMP_PRO_MAPPINGS,
  },
};